### ISSUE TITLE
Static builds were recently broken

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#826]
Something recently broke static builds - which also breaks our nightly binary builds.

To reproduce, configure e.g. with
```
./configure --prefix=$HOME/zeek/install-master --binary-package --enable-static-broker --enable-static-binpac --generator=Ninja --enable-debug --build-type=debug
```

This will result in a whole bunch of errors like this:
```
[704/1140] Linking CXX executable aux/broker/doc/_examples/stores
FAILED: aux/broker/doc/_examples/stores
: && /usr/lib64/ccache/c++  -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -Wno-register -std=c++17 -g  -rdynamic aux/broker/doc/_examples/CMakeFiles/stores.dir/stores.cc.o  -o aux/broker/doc/_examples/stores  aux/broker/libbroker.a  aux/broker/3rdparty/caf/lib/libcaf_openssl_static.a  -lssl  -lcrypto  aux/broker/3rdparty/caf/lib/libcaf_io_static.a  aux/broker/3rdparty/caf/lib/libcaf_core_static.a && :
/usr/bin/ld: aux/broker/libbroker.a(sqlite3.c.o): undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
/usr/bin/ld: //usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Jon flagged that this may be caused by https://github.com/zeek/broker/pull/87

**Comment by 0xxon** [comment]
Note that there was some discussion in https://github.com/zeek/broker/pull/87 around the pthread flag.

**Comment by jsiwek** [comment]
@Neverlord can you take a look?  At least part of solution may be moving that `-pthread` setting to a spot where submodule builds still find it.  E.g. a "quick" fix:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt                                              
index deb5e7a..d3b3391 100644                                                   
--- a/CMakeLists.txt                                                            
+++ b/CMakeLists.txt                                                            
@@ -71,11 +71,6 @@ if (NOT broker_is_subproject)                                
       endif ()                                                                 
   endif()                                                                      
                                                                                
-  # Mac OS ignores -pthread but other platforms require it                     
-  if (NOT BROKER_APPLE)                                                        
-    set(EXTRA_FLAGS "${EXTRA_FLAGS} -pthread")                                 
-  endif ()                                                                     
-                                                                               
   # Increase warnings.                                                         
   set(EXTRA_FLAGS "${EXTRA_FLAGS} -Wall -Wno-unused -pedantic")                
                                                                                
@@ -92,6 +87,13 @@ endif()                                                      
                                                                                
 include(RequireCXX17)                                                          
                                                                                
+if (NOT BROKER_DISABLE_PTHREADS_FLAG)                                          
+  # Mac OS ignores -pthread but other platforms require it                     
+  if (NOT BROKER_APPLE AND NOT WIN32)                                          
+    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")                         
+  endif ()                                                                     
+endif ()                                                                       
+                                                                               
 if (NOT BROKER_DISABLE_SSE2_CHECK)                                             
                                                                                
   include(CheckIncludeFiles)
```

But also ultimateIy run into `-fPIC` issue that may need a CAF change:

```
/usr/bin/ld: error: aux/broker/3rdparty/caf/lib/libcaf_core_static.a(test_actor_clock.cpp.o): requires dynamic R_X86_64_PC32 reloc against '_ZTVN3caf6detail16test_actor_clockE' which may overflow at runtime; recompile with -fPIC
collect2: error: ld returned 1 exit status
```

**Comment by Neverlord** [comment]
Should be fixed via https://github.com/zeek/broker/pull/94. However, I wonder why the CI didn't find this earlier. Does the build matrix omit static builds?

**Comment by jsiwek** [comment]
> Should be fixed via [zeek/broker#94](https://github.com/zeek/broker/pull/94). However, I wonder why the CI didn't find this earlier. Does the build matrix omit static builds?

Thanks.  CI doesn't currently test a static build (but now an item on my todo list).

**Comment by jsiwek** [comment]
@0xxon of course, inform if still broken for you
