### PR TITLE
Remove unused includes from various files

### PR DESCRIPTION
**Pull request by timwoj**
I ran across a few of these while working on security tickets and a few more while working on the 9.1 deprecation removals. This goes through the code and removes any include directive that appears entirely unused by the file that adds it.

### CODE REVIEW

**Comment by 0xxon** [comment]
Seems like Ubuntu 24.04 wants one more include :)

**Comment by awelzel** [comment]
> Seems like Ubuntu 24.04 wants one more include :)

Ha, racing here :-)


The clang-tidy-diff check bails because it fails against the `Binary.h` header:

```
$ clang-tidy -p build/ src/input/readers/binary/Binary.h
10866 warnings and 1 error generated.
Error while processing /home/awelzel/corelight-oss/zeek/src/input/readers/binary/Binary.h.
/home/awelzel/corelight-oss/zeek/src/include/zeek/IntrusivePtr.h:118:17: error: no matching function for call to 'Unref' [clang-diagnostic-error]
  118 |                 Unref(ptr_);
      |                 ^~~~~
/home/awelzel/corelight-oss/zeek/src/include/zeek/IntrusivePtr.h:72:55: note: in instantiation of member function 'zeek::IntrusivePtr<zeek::EnumType>::~IntrusivePtr' requested here
   72 |     constexpr IntrusivePtr(std::nullptr_t) noexcept : IntrusivePtr() {
      |                                                       ^
/home/awelzel/corelight-oss/zeek/src/include/zeek/Obj.h:199:13: note: candidate function not viable: cannot convert argument of incomplete type 'pointer' (aka 'zeek::EnumType *') to 'Obj *' for 1st argument
  199 | inline void Unref(Obj* o) {
      |             ^     ~~~~~~
Suppressed 10889 warnings (10864 in non-user code, 23 NOLINT, 2 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
```

This seems to stem from plugin/Component.h and the following appears to fix it:

```
 git d src/plugin/Component.h 
diff --git a/src/plugin/Component.h b/src/plugin/Component.h
index de2e167181..a868048eae 100644
--- a/src/plugin/Component.h
+++ b/src/plugin/Component.h
@@ -6,14 +6,11 @@
 
 #include "zeek/IntrusivePtr.h"
 #include "zeek/Tag.h"
+#include "zeek/Type.h"
 
 namespace zeek {
 
 class ODesc;
-class EnumType;
-using EnumTypePtr = IntrusivePtr<EnumType>;
-class EnumVal;
-using EnumValPtr = IntrusivePtr<EnumVal>;
 class StringVal;
 using StringValPtr = IntrusivePtr<StringVal>;
```

---

Now I'm not sure. Do we expect clang-tidy to pass when running against headers only? I suppose that `./configure --enable-clang-tidy` only runs against `.cc` files. And again, that `clang-tidy-diff.py` addition was a "lets try to catch stuff early", but if it hurts too much, can drop it again.

**Comment by timwoj** [comment]
Fixed that, and also a missing include of `chrono` for Windows.

**Review by awelzel — APPROVED** [review]
