### ISSUE TITLE
zeek does not build with >pybind-2.5.0

### ISSUE THREAD

**Issue by vklimovs** [zeek/zeek#1340]
zeek 3.0.11, 3.0.12, 3.2.2, 3.2.3 does not build with >pybind-2.5.0, with many errors:

/var/tmp/portage/net-analyzer/zeek-3.0.11/work/zeek-3.0.11/aux/broker/bindings/python/set_bind.h:9:16: error: expected constructor, destructor, or type conversion before ‘(’ token
    9 | NAMESPACE_BEGIN(pybind11)
      |                ^
/var/tmp/portage/net-analyzer/zeek-3.0.11/work/zeek-3.0.11/aux/broker/bindings/python/set_bind.h:26:32: error: variable or field ‘set_if_copy_constructible’ declared void
   26 | void set_if_copy_constructible(enable_if_t<
      |                                ^~~~~~~~~~~
/var/tmp/portage/net-analyzer/zeek-3.0.11/work/zeek-3.0.11/aux/broker/bindings/python/set_bind.h:26:32: error: ‘enable_if_t’ was not declared in this scope; did you mean ‘pybind11::detail::enable_if_t’?
   26 | void set_if_copy_constructible(enable_if_t<
      |                                ^~~~~~~~~~~
      |                                pybind11::detail::enable_if_t

**Comment by vklimovs** [comment]
Full build log:

[build.log](https://github.com/zeek/zeek/files/5718095/build.log)

**Comment by jsiwek** [comment]
This should be fixed in `master` branch and the upcoming 4.0.0 by this patch: https://github.com/zeek/broker/pull/152/files
(not expecting any 3.x.y release will be made that has it)
