### ISSUE TITLE
Statically-linked zeek binary from Debian_12 debs missing symbol(s) used by spicy

### ISSUE THREAD

**Issue by mmguero** [zeek/zeek#3177]
Steps to reproduce (uses a provided Dockerfile, but likely could produce on any Debian 12 system using the 6.0.0 release .deb files from opensuse.org)

1. Download this [Dockerfile](https://github.com/zeek/zeek/files/11970377/Dockerfile.txt)
    * This Dockerfile is a bare-bones bookworm-slim image that installs minimum packages needed to download the Zeek 6.0.0 debs from [opensuse.org](https://download.opensuse.org/repositories/security:/zeek/Debian_12)
1. `docker build -t zeek-spicy-crash .`
1. `docker run -Pit --rm --entrypoint=/bin/bash zeek-spicy-crash`
1. `zkg install --skiptests --force https://github.com/cisagov/icsnpp-synchrophasor`
    * I'm not sure what is special about this parser, but one of my other parsers, `cisagov/icsnpp-genisys`, does not reproduce the problem
1. `zeek -NN local`

Observed behavior:

```
# zeek -NN local
[libhilti] Fatal error: could not open library path "/opt/zeek/lib/zeek/plugins/packages/icsnpp-synchrophasor/synchrophasor.hlto":
failed to load library "/opt/zeek/lib/zeek/plugins/packages/icsnpp-synchrophasor/synchrophasor.hlto":
/opt/zeek/lib/zeek/plugins/packages/icsnpp-synchrophasor/synchrophasor.hlto:
undefined symbol: _ZN5hilti2rt4real6unpackERKNS0_6stream4ViewENS1_4TypeENS0_9ByteOrderE
```

Expected behavior: For `zeek` to run and output the list of available analyzers

Discussed in Slack in a thread in the #spicy channel with @bbannier and @0xxon

**Comment by bbannier** [comment]
[`Dockerfile`](https://github.com/zeek/zeek/files/11970576/Dockerfile.txt)

**Comment by mmguero** [comment]
Apparently also a problem with `spicy-http`

**Comment by JustinAzoff** [comment]
Interesting.. I had been playing around with some `nix` stuff to build zeek and spicy and a bunch of analyzers.  Things worked with 5.2.2, but when I switched to 6 analyzers fail with

```
[libhilti] Fatal error: could not open library path ".../wireguard.hlto": failed to load library "/.../wireguard.hlto": .../wireguard.hlto: undefined symbol: _ZN5spicy2rt4Sink6_closeEb
```

I have a feeling it's related to nix `strip`ing things, but attempts to tell it not to do that haven't helped.

I had figured I messed up something and this was a weird nix specific issue, but thought I'd mention it since it looks very similar to this issue with the Debian packages.

**Comment by 0xxon** [comment]
OBS uses the following configure:

```./configure --prefix=/opt/zeek-nightly --libdir=/opt/zeek-nightly/lib --binary-package --enable-static-broker --enable-static-binpac --disable-broker-tests```

If you use this (without the `--prefix` and `--libdir`, those should be unimportant), you should get an equivalent installation.

**Comment by bbannier** [comment]
Thanks for the flags, this does reproduce with above Dockerfile when using similar flags; `--binary-package --enable-static-broker --enable-static-binpac` is sufficient.

**Comment by bbannier** [comment]
Reopening as @mmguero reporting on [Slack](https://zeekorg.slack.com/archives/C012CQV1K29/p1694619035891959) that this is still an issue with 6.0.1.

**Comment by mmguero** [comment]
what I did, on a Debian 12 system (in Docker):

```
$ apt-get update
$ export ZEEK_VERSION=6.0.1-0
$ curl -sSL --remote-name-all \
  "https://download.opensuse.org/repositories/security:/zeek/Debian_12/amd64/libbroker-dev_${ZEEK_VERSION}_amd64.deb" \
  "https://download.opensuse.org/repositories/security:/zeek/Debian_12/amd64/zeek-core-dev_${ZEEK_VERSION}_amd64.deb" \
  "https://download.opensuse.org/repositories/security:/zeek/Debian_12/amd64/zeek-core_${ZEEK_VERSION}_amd64.deb" \
  "https://download.opensuse.org/repositories/security:/zeek/Debian_12/amd64/zeek-spicy-dev_${ZEEK_VERSION}_amd64.deb" \
  "https://download.opensuse.org/repositories/security:/zeek/Debian_12/amd64/zeek_${ZEEK_VERSION}_amd64.deb" \
  "https://download.opensuse.org/repositories/security:/zeek/Debian_12/amd64/zeekctl_${ZEEK_VERSION}_amd64.deb" \
  "https://download.opensuse.org/repositories/security:/zeek/Debian_12/all/zeek-client_${ZEEK_VERSION}_all.deb" \
  "https://download.opensuse.org/repositories/security:/zeek/Debian_12/all/zeek-zkg_${ZEEK_VERSION}_all.deb" \
  "https://download.opensuse.org/repositories/security:/zeek/Debian_12/all/zeek-btest_${ZEEK_VERSION}_all.deb" \
  "https://download.opensuse.org/repositories/security:/zeek/Debian_12/all/zeek-btest-data_${ZEEK_VERSION}_all.deb"
$ dpkg -i *.deb
$ apt-get -f install
$ export PATH=/opt/zeek/bin:$PATH
$ zeek --version
zeek version 6.0.1
```

I then installed the various debs for building spicy packages.

Then,

```
$ zkg install --force --skiptests corelight/zeek-spicy-wireguard
Installing "zeek/corelight/zeek-spicy-wireguard"...............
Installed "zeek/corelight/zeek-spicy-wireguard" (v0.1.3)
Loaded "zeek/corelight/zeek-spicy-wireguard"

$ zeek -NN
[libhilti] Fatal error: could not open library path "/opt/zeek/lib/zeek/plugins/packages/zeek-spicy-wireguard/wireguard.hlto": failed to load library "/opt/zeek/lib/zeek/plugins/packages/zeek-spicy-wireguard/wireguard.hlto": /opt/zeek/lib/zeek/plugins/packages/zeek-spicy-wireguard/wireguard.hlto: undefined symbol: _ZN5spicy2rt4Sink6_closeEb
```

**Comment by mmguero** [comment]
I see this was moved to 6.2, but I just wanted to chime in and confirm that this is still a problem with the v6.1 release (as we expected it would be). So for the time being I'll just continue building my own packages from source.

**Comment by timwoj** [comment]
> I see this was moved to 6.2, but I just wanted to chime in and confirm that this is still a problem with the v6.1 release (as we expected it would be). So for the time being I'll just continue building my own packages from source.

It got moved because we ran out of time to work on it for 6.1 but it's still a priority enough to get it done that it can stay on the board. It's likely that we can backport it to 6.1 once it's fixed during the 6.2 cycle, prior to 6.2 coming out.

**Comment by 0xxon** [comment]
Hi,

I took a peek at this today. I can confirm that this is still a problem.

It turns out that all the. necessary sumbols are actualy contained in `libspicy-rt.a`. They are not contained in either the Zeek executable (because Zeek does not require them), nor in the .hlto file for the parser (because they can't be - otherwise there would be duplicate symbols when loading several parsers).

A solution to this seems to be to force Zeek to include the symbols that are part of `libspicy-rt.a`. I verified this by manually altering the compile command for the Zeek executable. If one appends...

```
 -Wl,--push-state,--whole-archive auxil/spicy/spicy/runtime/CMakeFiles/spicy-rt-objects.dir/src/base64.cc.o   auxil/spicy/spicy/runtime/CMakeFiles/spicy-rt-objects.dir/src/sink.cc.o auxil/spicy/spicy/runtime/CMakeFiles/spicy-rt-objects.dir/src/util.cc.o auxil/spicy/spicy/runtime/CMakeFiles/spicy-rt-objects.dir/src/zlib.cc.o auxil/spicy/spicy/runtime/CMakeFiles/spicy-rt-objects.dir/__/__/3rdparty/libb64/src/cdecode.c.o auxil/spicy/spicy/runtime/CMakeFiles/spicy-rt-objects.dir/__/__/3rdparty/libb64/src/cencode.c.o -Wl,--no-whole-archive
```

to it, the resulting Zeek executable will be able to load parsers that errored out before without any problems.

The --whole-archive option forces ld to include all symbols, even if not required by Zeek; the list of object files was generated by taking the list of all object files that are in `libspicy-rt`, and then manually removing some that caused duplicate symbol errors during the link process.

I am admittedly not familiar enough with cmake to know how to get it to do this - but if we figure that out, this issue might be solved.
