### PR TITLE
Implement tail -F semantics for input framework MODE_STREAM

### PR DESCRIPTION
**Pull request by leres**
Open /dev/null if the file is missing during init and wait for file to be created. Collect initial ino, dev, and mtime when first opening the file. Detect if the file has been replaced and open the new version.

This is my initial attempt to solve issue  #2028 and does not include documentation changes.

### CODE REVIEW

**Comment by leres** [comment]
I don't understand how to see details for the check that failed and when I try to build on FreeBSD 12.3 I get errors from completely unrelated modules (e.g. auxil/c-ares).

Unfortunately the machine I can build/test on does not have a default route and cannot talk to github; the system I can talk to github on cannot build zeek.

**Comment by leres** [comment]
Here's the script I have been testing with:
```
module test;

redef exit_only_after_terminate=T;

export {
        type lineVals: record {
                d: string;
        };
        global test_file = "/tmp/test.log";
}

function
lg(s: string)
{
        print s;
}

event
test_data(description: Input::EventDescription, tpe: Input::Event,
    line: lineVals)
{
        lg(fmt("=> %s", line$d));
}

event
zeek_init()
{
        lg("zeek_input: test-inputframework ");
        local config_strings: table[string] of string = {
                ["offset"] = "-1",
        };
        Input::add_event([$source=test_file, $name="RawAuthData",
            $fields=lineVals, $ev=test_data, $config=config_strings,
            $reader=Input::READER_RAW, $mode=Input::STREAM]);
}

event
zeek_done()
{
        lg("zeek_done: test-inputframework ");
}
```

**Comment by timwoj** [comment]
> I don't understand how to see details for the check that failed

Unfortunately, you can't see more details for the failed tests from Cirrus than what is shown on the build pages (https://cirrus-ci.com/task/4967375660384256?logs=test#L24, for example). It looks like `scripts.base.frameworks.input.raw.rereadraw` is failing on basically every host though, so that's probably something caused by your change.

>  when I try to build on FreeBSD 12.3 I get errors from completely unrelated modules (e.g. auxil/c-ares).

What errors are you seeing with c-ares? It should build on basically anything we support without any failures.

**Comment by leres** [comment]
It builds on a 12.3 system (after installing swig) but not on Aashish's 12.2 test box, at least not with "make -j32". I started a non-parallel build but it's really slow (this system is pretty loaded). But the 12.3 system runs my test script ok.

It sounds like I've broken MODE_REREAD, let me do some testing with 4.2.1 (which does build on this system) and report back.

**Comment by timwoj** [comment]
> but not on Aashish's 12.2 test box, at least not with "make -j32"

What error is it reporting? I just built `master` recently with `make -j20` on a system and it didn't have any problems in c-ares, so I can't imagine it's the parallel build causing it.

**Comment by leres** [comment]
Here's the error:
```
[ 29%] Building C object auxil/c-ares/src/lib/CMakeFiles/c-ares.dir/ares__addrinfo2hostent.c.o
/home/leres/TEST/zeek-master.git/auxil/c-ares/src/lib/ares__addrinfo2hostent.c:132:41: error: no member named 'name' in 'struct ares_addrinfo'
      (*host)->h_name = ares_strdup(ai->name);
                                    ~~  ^
/home/leres/TEST/zeek-master.git/auxil/c-ares/src/lib/ares__addrinfo2hostent.c:133:42: error: no member named 'name' in 'struct ares_addrinfo'
      if ((*host)->h_name == NULL && ai->name)
                                     ~~  ^
2 errors generated.
*** Error code 1
```
Keep in mind this is a FreeBSD 12.2, which is no longer supported.  That said I don't even see auxil/c-ares in the 4.2.1 tree. But I do see where that module built on my 12.3 system.

I don't think this issue is worth spending a lot of time on, I'm more concerned about the test failures so let me try to reproduce the MODE_REREAD failure. I only intended to change MODE_STREAM but maybe there's an unintended change I don't see yet.

**Comment by timwoj** [comment]
> That said I don't even see auxil/c-ares in the 4.2.1 tree.

The c-ares work was merged maybe 3 weeks ago, so it's brand new for 5.0. It's curious that that doesn't build though, as the variable should definitely be there. If you don't think it's a big deal I'll shove it down the pile to look at later.

**Comment by vpax** [comment]
@leres FWIW this bit me a couple of weeks ago, and ultimately I discovered it's because I already had (an old version of) c-ares installed on the system and the headers from that were being found rather than those for auxil/c-ares/.

**Comment by leres** [comment]
> @leres FWIW this bit me a couple of weeks ago, and ultimately I discovered it's because I already had (an old version of) c-ares installed on the system and the headers from that were being found rather than those for auxil/c-ares/.

That's it, thanks!
```
adhoc 291 % pkg info | fgrep c-ares
c-ares-1.17.2                  Asynchronous DNS resolver library
```

**Comment by leres** [comment]
Here's a better version. I lucked out and Aashish already had btest installed and I was able to generate the failure with the 4.2.1 tree. I can't tell if the ci test has failed again or if it's still running. But all of the frameworks/input/raw pass locally.

A note about btest, it doesn't work that well when working on an nfs filesystem, it seems to always generate "directory not empty"  errors.

Regarding an older c-ares installed in the base system, I would argue that if you're going to bundle c-ares, you should be careful to put the bundled include tree in the include file search path before /usr/local/include. (The same goes for the library.)

**Comment by leres** [comment]
So I think I won't be able to make forward progress until I can build on a system that has an older c-ares installed in /usr/local  (and this is worth fixing on its own).

What I've found is that auxil/c-ares/src/lib/CMakeFiles/c-ares.dir/flags.make defines C_INCLUDES and puts -I/usr/local/include before -I/home/leres/TEST/leres-zeek.git/auxil/c-ares/include:
```
-I/home/leres/TEST/leres-zeek.git/auxil/rapidjson/include
-I/home/leres/TEST/leres-zeek.git/auxil/paraglob/include
-I/home/leres/TEST/leres-zeek.git/auxil/highwayhash
-I/home/leres/TEST/leres-zeek.git/build/auxil/broker/include
-I/home/leres/TEST/leres-zeek.git/auxil/broker/include
-I/usr/local/include
-I/home/leres/TEST/leres-zeek.git/build/auxil/binpac/lib
-I/home/leres/TEST/leres-zeek.git/auxil/binpac/lib
-I/home/leres/TEST/leres-zeek.git/build/auxil/c-ares
-I/home/leres/TEST/leres-zeek.git/auxil/c-ares
-I/home/leres/TEST/leres-zeek.git/auxil/c-ares/include
-I/home/leres/TEST/leres-zeek.git/auxil/c-ares/src/lib/include
```
But I don't understand what determines the order so I don't know how to change it.

**Comment by initconf** [comment]
> adhoc 291 % pkg info | fgrep c-ares
> c-ares-1.17.2                  Asynchronous DNS resolver library

I've fixed this now! no longer an issue !

**Comment by leres** [comment]
> > adhoc 291 % pkg info | fgrep c-ares
> > c-ares-1.17.2                  Asynchronous DNS resolver library
> 
> I've fixed this now! no longer an issue !

I would argue the whole point of bundling c-ares with zeek is so that it doesn't matter which version is installed on the operating system. And I think we have a fix for that.

**Review by 0xxon — COMMENTED** [review]
One small question. `MODE_STREAM` is currently mostly used with pipes, when executing other processes (e.g. by the Exec framework). Do you see any chance that this change could lead to any problems with this, or to repeated execution? I assume no, but I am honestly not entirely sure how, e.g., a stat on a pipe (which is used to see if the file has changed) behaves.

File: src/input/readers/raw/Raw.cc [hunk 1]
```diff
@@ -574,25 +596,54 @@ bool Raw::DoUpdate()
...
+				// File was replaced
+				FILE* tfile;
+				tfile = fopen(fname.c_str(), "r");
+				if ( ! tfile )
+					break;
+
+				// Stat newly opened file
+				if ( fstat(fileno(tfile), &sb) == -1 )
+					{
+					Error(Fmt("Could not fstat %s", fname.c_str()));
```
[the remark this answers is not in the document]
Comment (leres) [reply src/input/readers/raw/Raw.cc:636]: Doing a fstat() of a file that was just opened "should never fail" but I always to to check syscall returns for errors. I'll look at this a bit more.

**Comment by timwoj** [comment]
I'm going to hold off on merging this for 5.0. We'll likely do a 5.0.1 release shortly after (as is typical for x.0 releases), so we can get it into that once it's merged into master.

**Comment by leres** [comment]
> the specific case I was thinking about is when the Raw reader is used to execute a command in `Raw::Execute`; `testing/btest/scripts/base/frameworks/input/raw/executestream.zeek` is a test that exercises that, e.g..

Interesting. The test shows a workaround for @initconf and I to get "tail -F" semantics:

    `Input::add_event([$source="tail -F file.log |", $reader=Input::READER_RAW` [...]

Anyway, what do you think about not going down my (new) "tail -F" code path if S_ISFIFO() is false? Or maybe there's a better test? Certainly  try to stat() and fopen() fname.c_str() aren't going to work when we have a pipe. (Do we even have `fname` when we are reading from a pipe?)

Either way, more stuff for me to poke at, thanks!

**Comment by 0xxon** [comment]
> Anyway, what do you think about not going down my (new) "tail -F" code path if S_ISFIFO() is false? Or maybe there's a better test? 

No - I think it is fine. I just might feel a bit better if there is an additional check that does not use the new codepath if a program was executed in stream mode though. Just to prevent something really ridiculous (think - someone purposefully making a file that has the same name as one of the pipes).

That being said, it should also be fine as it is at the moment.

**Comment by timwoj** [comment]
@0xxon Are you ok with this then? Want to give it an official review?

**Comment by leres** [comment]
> @0xxon Are you ok with this then? Want to give it an official review?

(I think we're waiting for me to get a couple of minutes to see if there are any changes I can make to address the issues she brought up.)

**Comment by timwoj** [comment]
Ok great. Just trying to keep on top of what the status on it is 😃

**Comment by leres** [comment]
I'm pretty happy with this version. It definitely was not correct to stat() "file" when execute is true.

**Review by 0xxon — APPROVED** [review]
